// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 16.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CLIF.Codegenerator
{
    using System;
    using System.IO;
    using System.Diagnostics;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class LinqModificationTemplate : LinqModificationTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(" \r\n");
            
            #line 11 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"


            
            #line default
            #line hidden
            this.Write("//This file is automatically generated from the CLIF code generator\r\n\r\nusing Syst" +
                    "em;\r\nusing System.Linq;\r\nusing System.Collections;\r\nusing System.Collections.Gen" +
                    "eric;\r\n\r\nusing Xbim.Ifc;\r\nusing Xbim.Common;\r\n\r\nusing CLIF.Common;\r\n\r\nnamespace " +
                    "");
            
            #line 24 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic class ");
            
            #line 26 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 26 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LinqModificationTemplate.interfaceType.FullName));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\t");
            
            #line 28 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
 
			string finalParamString = "";
			string storeName = "ifcStore";
			string entitiesName = "entitiesToUpdate";
			foreach (System.Reflection.ParameterInfo paramInfo in LinqModificationTemplate.interfaceMethod.GetParameters())
            {
				string paramString;
				if (paramInfo.ParameterType.IsGenericType)
                {
                    paramString = paramInfo.ParameterType.FullName.Split("`")[0] + "<";
					paramString = paramString + string.Join(",", paramInfo.ParameterType.GenericTypeArguments.Select(x => x.FullName));
					paramString = paramString + "> " + paramInfo.Name;
					entitiesName = paramInfo.Name;
                }
                else
                {
					paramString = string.Join(" ", paramInfo.ParameterType.FullName, paramInfo.Name);
					if (paramInfo.ParameterType.Equals(typeof(Xbim.Ifc.IfcStore)))
                    {
						storeName = paramInfo.Name;
                    }
                }

				if (string.IsNullOrWhiteSpace(finalParamString))
                {
					finalParamString = paramString;
                }
                else
                {
					finalParamString = finalParamString + ", " + paramString;
                }
            }
			
			Type returnType = LinqModificationTemplate.interfaceMethod.ReturnType;
			string returnTypeString;
			if (returnType.IsGenericType)
            {
				Type[] genericArguments = returnType.GetGenericArguments();
				returnTypeString = LinqModificationTemplate.interfaceMethod.ReturnType.Name.Split('`')[0] + 
					"<" + string.Join(",", genericArguments.Select(x => x.Name)) + ">";
            }
			else
            {
                if (LinqModificationTemplate.interfaceMethod.ReturnType.Equals(typeof(void)))
                {
					returnTypeString = LinqModificationTemplate.interfaceMethod.ReturnType.Name.ToLower();
                }
				else
                {
					returnTypeString = LinqModificationTemplate.interfaceMethod.ReturnType.Name;
				}
            }
		
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 82 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
string nameInternalMethod = "InternalUpdateMethod";
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 84 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(returnTypeString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 84 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LinqModificationTemplate.interfaceMethod.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 84 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(finalParamString));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\t");
            
            #line 86 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(storeName));
            
            #line default
            #line hidden
            this.Write(".ForEach<");
            
            #line 86 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.InputParameterTypeFullName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 86 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitiesName));
            
            #line default
            #line hidden
            this.Write(".Cast<");
            
            #line 86 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.InputParameterTypeFullName));
            
            #line default
            #line hidden
            this.Write(">(), ");
            
            #line 86 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nameInternalMethod));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t}\r\n\r\n\t\tprivate void ");
            
            #line 89 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nameInternalMethod));
            
            #line default
            #line hidden
            this.Write(" (");
            
            #line 89 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.InputParameterTypeFullName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 89 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UpdateEntityName));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\t");
            
            #line 91 "C:\Users\ripo9018\source\repos\IfcQueryLanguage\CLIF.codegenerator\LinqModificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.MethodBody));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t}\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class LinqModificationTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
